config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
    member do
      #this references to the complete action controller
      patch :complete
    end

  end

  root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  # if completed_at is not null

  def completed?
    !completed_at.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :find_item, only: [:show, :edit, :update, :destroy, :complete]

  def index
    # @items = Item.all.order('created_at DESC')

    # displays user items if user is logged in
    if user_signed_in?
      @items = Item.where(:user_id => current_user.id).order('created_at DESC')
    end
  end

  def show
  end

  def new
    # @item = Item.new
    @item = current_user.items.build
  end

  def create
    # @item = Item.new(params_item)
    @item = current_user.items.build(params_item)

    if @item.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @item.update(params_item)
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end

  def destroy
    @item.destroy
    redirect_to root_path
  end

  def complete
    # this method update the completed_at attr with time now
    # after user checks the box and redirects to the index page
    @item.update_attribute(:completed_at, Time.now)
    redirect_to root_path
  end

  private
    def params_item
      params.require(:item).permit(:title, :description)
    end

    def find_item
      @item = Item.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.slim
div.col-md-6.col-md-offset-3
  = simple_form_for @item do |f|
    = f.input :title, label: 'Item'
    = f.input :description
    = f.button :submit

app/views/items/edit.slim
= render 'form'

app/views/items/index.slim
- if user_signed_in? 
  div.col-md-6.col-md-offset-3
    - @items.each do |item|
    
      / this if statement references to method in the item model
      - if item.completed?
        
        div.row
          div.col-md-8
            / h2= link_to item.title, item_path(item)
            h2.item-title.title-opac
              strike= link_to item.title, item_path(item)
              
            p.title-opac.time-ago.item-sub-title
              | Completed #{time_ago_in_words(item.completed_at)}
              
          div.col-md-2
            / = link_to "Mark as complete", complete_item_path(item), method: :patch, class: 'btn btn-primary btn-space'
            p
              = link_to complete_item_path(item), method: :patch do
                i.fa.fa-lg.fa-check
            
          div.col-md-2  
            / = link_to "Delete", item, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-primary btn-space'
            p
              = link_to item, method: :delete, data: {confirm: "Are you sure?"} do
                i.fa.fa-lg.fa-trash
      -else
        
        div.row
          div.col-md-8
            / h2= link_to item.title, item_path(item)
            h2.item-title
              = link_to item.title, item_path(item)
              
            p.title-opac.time-ago.item-sub-title
              | Created #{time_ago_in_words(item.created_at)}
              
          div.col-md-2
            / = link_to "Mark as complete", complete_item_path(item), method: :patch, class: 'btn btn-primary btn-space'
            p
              = link_to complete_item_path(item), method: :patch do
                i.fa.fa-lg.fa-check
            
          div.col-md-2  
            / = link_to "Delete", item, method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-primary btn-space'
            p
              = link_to item, method: :delete, data: {confirm: "Are you sure?"} do
                i.fa.fa-lg.fa-trash
    
- else
  = render 'layouts/front_page'

app/views/items/new.slim
= render 'form'

app/views/items/show.slim
div.col-md-6.col-md-offset-3
  h2= @item.title
  p= @item.description

  = link_to 'Back', root_path, class: 'btn btn-primary btn-space'

  = link_to 'Edit', edit_item_path(@item), class: 'btn btn-primary btn-space'

  = link_to 'Delete', item_path(@item), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-primary btn-space'

app/views/layouts/_front_page.slim
div.jumbotron
  h1 Welcome to Checklist App
  p Keeping track of your list has never been easier!

  = link_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg btn-space'
  
  = link_to 'Sign In', new_user_session_path, class: 'btn btn-primary btn-lg btn-space'
  

app/views/layouts/application.slim
DOCTYPE
html
head
  title ChecklistApp
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true 
  = csrf_meta_tags
  link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"

body
  nav.navbar.navbar-default
    div.container
      div.navbar-header
        = link_to 'Checklist', root_path, class: 'navbar-brand'
      
      ul.nav.navbar-nav
        - if current_user.present?
          li= link_to 'Sign Out', destroy_user_session_path, method: :delete
        - else
          li= link_to 'Sign Up', new_user_registration_path
          li= link_to 'Sign In', new_user_session_path
          
      - if user_signed_in?
        = link_to 'New Item', new_item_path, class: 'navbar-text navbar-link navbar-right'
  
  p.notice= notice
  p.alert= alert

  div.container
    = yield